### ISSUE TITLE
mru calibrate -i *.png failes with "Instrument Unknown!"

### ISSUE THREAD

**Issue by sschmaus** [kmgill/mars-raw-utils#14]
Running `m20_hnav_calibrate -i *.png` on previous versions on a folder with images performed calibration for all images in one go. 

I expect the same behavior with the current `mru calibrate -i *.png`, however it throws the following error: 
```powershell
mru calibrate -i *.png
*.png - Error: Instrument Unknown!        [ FAIL ]
```

At the moment I can only calibrate images if I include all filenames in the command, e.g.: `mru calibrate -i .\HNM_0414_0703689998_109ECM_N0260001HELI05210_0000A0J02.png .\HNM_0414_0703689998_706ECM_N0260001HELI05228_0000LUJ01.png .\HNM_0414_0703689998_109ECM_N0260001HELI05210_0000A0J02.png`

I would like to see the old behavior reintroduced, in case this isn't a bug. Calibrating the images one by one or adding all the filenames is quite tedious. 

## Specifications
  - Version: 0.5.0
  - Platform: Windows

**Comment by kmgill** [comment]
I'm not sure why the wildcard isn't working as I did not remove that. Will test

**Comment by kmgill** [comment]
Oh, when I updated the `clap` library I forgot to filter the args through `wild`. Whoops

**Comment by kmgill** [comment]
Changed from `Cli::parse()` to `Cli::parse_from(wild::args)` which will put the wildcard expansion back in there as expected. I will need to test on Windows

**Comment by kmgill** [comment]
Ok, works in Windows. Since this is a particularly annoying issue, I'll cut a 0.5.1 release for this and the previous bugfix from this morning.

**Comment by sschmaus** [comment]
Thanks for the quick fix and release!
